### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by ashishupadhyaa** [atom-community/atom-script#1454]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 ia32
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.17.2

### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At C:\Users\user\.atom\packages\script\lib\runner.js:137

TypeError: Cannot read property 'replace' of undefined
    at Runner.fillVarsInArg (/packages/script/lib/runner.js:137:16)
    at /packages/script/lib/runner.js:154:34
    at Array.map (native)
    at Runner.args (/packages/script/lib/runner.js:154:18)
    at Runner.run (/packages/script/lib/runner.js:26:23)
    at Runtime.execute (/packages/script/lib/runtime.js:78:17)
    at HTMLElement.scriptRun (/packages/script/lib/script.js:98:40)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.21.1/resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.21.1/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.21.1/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:12.3.0 script:run (input.hidden-input)
```

### Non-Core Packages

```
script 3.17.2 
```

**Comment by RafZone** [comment]
any way to solve this?

**Comment by ereDaMeme** [comment]
i dont know but its annoying.

**Comment by Jabberquacker** [comment]
Same problem just happened to me, any way to solved it?

**Comment by RafZone** [comment]
I used cygwin to compile the c file instead and it worked. I don't know how to fix this in atom

**Comment by atom-xiaogoubi** [comment]
omg, the problem is so annoying

**Comment by Elia0107** [comment]
Same problem...

**Comment by chwdy** [comment]
Same problem...

**Comment by Mutawapre** [comment]
d = don't
l = love
p = problem
I d l p

**Comment by puneet29** [comment]
Try saving the file before compiling and running it.

Hope it helps!

**Comment by MeteorInfinity** [comment]
Same problem...

**Comment by AJohnWang** [comment]
i just got this problem too

**Comment by AJohnWang** [comment]
do anyone can solve it for us ?

**Comment by ak-ghoul** [comment]
What is the solution to this problem?

**Comment by senlos** [comment]
Maybe you try to run languages it couldn't support? Like C or C++.

**Comment by AmitMahato0208** [comment]
Please help me
