### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by J-Cake** [atom-community/atom-script#1722]
[Enter steps to reproduce:]

use it

**Atom**: 1.31.1 x64
**Electron**: 2.0.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.18.1

### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At C:\Users\Jacob Schneider\.atom\packages\script\lib\runner.js:137

TypeError: Cannot read property 'replace' of undefined
    at Runner.fillVarsInArg (/packages/script/lib/runner.js:137:17)
    at /packages/script/lib/runner.js:168:34
    at Array.map (<anonymous>)
    at Runner.args (/packages/script/lib/runner.js:168:18)
    at Runner.run (/packages/script/lib/runner.js:26:23)
    at Runtime.execute (/packages/script/lib/runtime.js:78:17)
    at HTMLElement.scriptRun (/packages/script/lib/script.js:98:40)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.31.1/resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.31.1/resources/app/src/command-registry.js:273:23)
    at ToolBarButtonView.executeCallback (/packages/tool-bar/lib/tool-bar-button-view.js:130:21)
    at ToolBarButtonView._onClick (/packages/tool-bar/lib/tool-bar-button-view.js:109:12)
```

### Commands

```
     -2:41.9.0 core:save (input.hidden-input)
     -2:41.8.0 editor:newline-below (input.hidden-input)
  2x -2:33.9.0 core:backspace (input.hidden-input)
     -2:33.2.0 core:save (input.hidden-input)
  4x -2:30.9.0 core:close (div.package-detail.panels-item)
     -2:23.7.0 script:run-options (input.hidden-input)
     -2:16.5.0 tree-view:copy-full-path (span.name.icon.icon-file-text)
     -2:15.3.0 core:paste (input.hidden-input)
  8x -2:12.8.0 core:backspace (input.hidden-input)
  2x -1:33.2.0 core:confirm (input.hidden-input)
     -1:27.7.0 editor:consolidate-selections (input.hidden-input)
     -1:27.7.0 core:cancel (input.hidden-input)
     -1:23.6.0 script:run-options (div.tool-panel.tree-view)
     -1:20.6.0 core:paste (input.hidden-input)
  8x -1:19.4.0 core:backspace (input.hidden-input)
 13x -1:00.2.0 script:run (atom-workspace.workspace.scrollbars-visible-always.theme-visual-studio-dark-syntax.theme-atom-material-ui)
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-ide-debugger-node 0.7.3 
atom-ide-debugger-python 0.7.3 
atom-ide-ui 0.13.0 
atom-material-ui 2.1.3 
atom-toolbar-preferred 1.4.1 
chrome-color-picker 0.8.0 
hex-view 0.2.1 
ide-css 0.3.0 
javascript-refactor 0.7.1 
language-arcs 0.0.0 
language-pug 0.0.22 
language-vb 0.1.0-pre1 
minimap 4.29.9 
night-terminal 1.1.1 
open-in-browsers 0.0.30 
refactor 0.11.5 
script 3.18.1 
split-diff 1.5.2 
statusbar-battery 0.11.3 
todo 0.6.0 
tool-bar 1.1.10 
visual-studio-dark-syntax 0.2.0 
```

**Comment by AwesomeTank9** [comment]
I got it too but I don't know how to fix it :(

**Comment by MartSmi** [comment]
Have the same issue

**Comment by Lorybat1998UCD** [comment]
Yeah same here.

**Comment by TeAmP0is0N** [comment]
yeah same here.

**Comment by TeAmP0is0N** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.18.1


### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At C:\Users\lucifer\.atom\packages\script\lib\runner.js:141

TypeError: Cannot read property 'replace' of undefined
    at Runner.fillVarsInArg (/packages/script/lib/runner.js:141:17)
    at /packages/script/lib/runner.js:168:34
    at Array.map (<anonymous>)
    at Runner.args (/packages/script/lib/runner.js:168:18)
    at Runner.run (/packages/script/lib/runner.js:26:23)
    at Runtime.execute (/packages/script/lib/runtime.js:78:17)
    at HTMLElement.scriptRun (/packages/script/lib/script.js:98:40)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:347327)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:1227611)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:1223745)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:282763)
```

### Commands

```
     -1:54 core:paste (input.hidden-input)
     -1:51.4.0 grammar-selector:show (atom-text-editor.editor.is-focused)
  2x -1:35.7.0 script:run (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-java 1.2.7 
gpp-compiler 3.0.7 
ide-java 0.8.3 
linter-gcc 0.7.1 
script 3.18.1 
```

**Comment by devashishkatoriya** [comment]
Same Issue

Uncaught TypeError: Cannot read property 'replace' of undefined
C:\Users\Devashish\.atom\packages\script\lib\runner.js:137

Stack Trace:
TypeError: Cannot read property 'replace' of undefined
    at Runner.fillVarsInArg (file:///C:/Users/Devashish/.atom/packages/script/lib/runner.js:137:17)
    at file:///C:/Users/Devashish/.atom/packages/script/lib/runner.js:168:34
    at Array.map (<anonymous>)
    at Runner.args (file:///C:/Users/Devashish/.atom/packages/script/lib/runner.js:168:18)
    at Runner.run (file:///C:/Users/Devashish/.atom/packages/script/lib/runner.js:26:23)
    at Runtime.execute (file:///C:/Users/Devashish/.atom/packages/script/lib/runtime.js:78:17)
    at HTMLElement.scriptRun (file:///C:/Users/Devashish/.atom/packages/script/lib/script.js:98:40)
    at CommandRegistry.handleCommandEvent (C:\Users\Devashish\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:350034)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (C:\Users\Devashish\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:1231386)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (C:\Users\Devashish\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:1227520)
    at WindowEventHandler.handleDocumentKeyEvent (C:\Users\Devashish\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:285213)

**Comment by devashishkatoriya** [comment]
I had this issue when I accidentally tried running C program with Script (Habitually, Ctrl+Shft+B). For running C/C++ program one needs Gpp-Compiler (Function key F5).

**Comment by KlaussMC** [comment]
I write a basic node script `let x = 10; console.log(x)`; and it fails me, the simplest of programs!

**Comment by LeenNabkie** [comment]
required

**Comment by mikcc123** [comment]
Yeah same here. Is there a solution?

**Comment by TeAmP0is0N** [comment]
No, I have not got any solution.

**Comment by mohammed-mossad** [comment]
> I had this issue when I accidentally tried running C program with Script (Habitually, Ctrl+Shft+B). For running C/C++ program one needs Gpp-Compiler (Function key F5).

you know i do the same thing form the start but i just wanted to try the script runner and i get that error fro c/c++ codes
