### ISSUE TITLE
Failed to activate the script package

### ISSUE THREAD

**Issue by AnnachiPSP** [atom-community/atom-script#2347]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home
**Thrown From**: [script](https://github.com/atom-ide-community/atom-script) package 3.29.3

### Stack Trace

Failed to activate the script package

```
At Cannot find module './code-context-builder'
Require stack:
- C:\Users\suryaprakash\.atom\packages\script\lib\script.js
- C:\Users\suryaprakash\AppData\Local\atom\app-1.53.0\resources\app.asar\static\index.html

Error: Cannot find module './code-context-builder'
Require stack:
- C:\Users\suryaprakash\.atom\packages\script\lib\script.js
- C:\Users\suryaprakash\AppData\Local\atom\app-1.53.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.53.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (<embedded>:11:155481)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (<embedded>:11:146814)
    at /packages/script/lib/script.js:9:27)
    at /packages/script/lib/script.js:277:3)
    at Module.get_Module._compile (<embedded>:11:147498)
    at Object.value [as .js] (<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (<embedded>:1:736531)
    at Package.requireMainModule (<embedded>:11:3711337)
    at Package.activateNow (<embedded>:11:3699321)
    at <embedded>:14:2607
    at Function.simpleDispatch (<embedded>:11:1190051)
    at Emitter.emit (<embedded>:11:1191492)
    at <embedded>:11:383812
    at Set.forEach (<anonymous>:null:null)
    at PackageManager.activatePackage (<embedded>:11:383774)
    at <embedded>:11:916621
    at r (<embedded>:11:911227)
    at s (<embedded>:14:1134640)
    at ChildProcess.<anonymous> (<embedded>:14:1134846)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)

```

### Commands

```
  9x -1:31.9.0 core:backspace (input.hidden-input)
     -1:00.2.0 Python run: run-f5 (input.hidden-input)
```

### Non-Core Packages

```
atom-python-run 0.9.7 
script 3.29.3 
```

**Comment by aminya** [comment]
Please reinstall. This is a connection issue.
