### ISSUE TITLE
Failed to activate the script package

### ISSUE THREAD

**Issue by kiannajimi** [atom-community/atom-script#2352]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: macOS 11.1
**Thrown From**: [script](https://github.com/atom-ide-community/atom-script) package 3.29.3

### Stack Trace

Failed to activate the script package

```
At Cannot find module 'uuid'
Require stack:
- /Users/kian/.atom/packages/atom-script-master/lib/grammar-utils.js
- /Users/kian/.atom/packages/atom-script-master/lib/grammars/index.coffee
- /Users/kian/.atom/packages/atom-script-master/lib/grammars.js
- /Users/kian/.atom/packages/atom-script-master/lib/code-context-builder.js
- /Users/kian/.atom/packages/atom-script-master/lib/script.js
- /Applications/Atom.app/Contents/Resources/app.asar/static/index.html

Error: Cannot find module 'uuid'
Require stack:
- /Users/kian/.atom/packages/atom-script-master/lib/grammar-utils.js
- /Users/kian/.atom/packages/atom-script-master/lib/grammars/index.coffee
- /Users/kian/.atom/packages/atom-script-master/lib/grammars.js
- /Users/kian/.atom/packages/atom-script-master/lib/code-context-builder.js
- /Users/kian/.atom/packages/atom-script-master/lib/script.js
- /Applications/Atom.app/Contents/Resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155481)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/atom-script-master/lib/grammar-utils.js:6:24)
    at /packages/atom-script-master/lib/grammar-utils.js:109:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/atom-script-master/lib/grammars/index.coffee:5:45)
    at /packages/atom-script-master/lib/grammars/index.coffee:4:1)
    at /packages/atom-script-master/lib/grammars/index.coffee:4:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/atom-script-master/lib/grammars.js:9:28)
    at /packages/atom-script-master/lib/grammars.js:1:13)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
```

### Commands

```
```

### Non-Core Packages

```
script 3.29.3 
darkpython-syntax 0.5.0 
```

**Comment by aminya** [comment]
Please reinstall. This is a connection issue.
