### ISSUE TITLE
Failed to activate the script package

### ISSUE THREAD

**Issue by Akimaru666** [atom-community/atom-script#2363]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: macOS 11.1
**Thrown From**: [script](https://github.com/atom-ide-community/atom-script) package 3.29.3

### Stack Trace

Failed to activate the script package

```
At Cannot find module './script-input-view'
Require stack:
- /Users/marcau/.atom/packages/script/lib/script-options-view.js
- /Users/marcau/.atom/packages/script/lib/script.js
- /Applications/Atom.app/Contents/Resources/app.asar/static/index.html

Error: Cannot find module './script-input-view'
Require stack:
- /Users/marcau/.atom/packages/script/lib/script-options-view.js
- /Users/marcau/.atom/packages/script/lib/script.js
- /Applications/Atom.app/Contents/Resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155481)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/script/lib/script-options-view.js:23:24)
    at /packages/script/lib/script-options-view.js:276:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/script/lib/script.js:29:26)
    at /packages/script/lib/script.js:277:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:696929)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3581148)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3569132)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1190051)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1191492)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:383812
    at Set.forEach (<anonymous>)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:383774)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:916621
    at r (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:911227)
    at s (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1134638)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1134792
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1133394)
    at Socket.emit (events.js:205:15)
    at Pipe.<anonymous> (net.js:586:12)
```

### Commands

```
  3x -3:31.8.0 core:close (input.hidden-input)
     -1:50.4.0 command-palette:toggle (div.package-detail)
  5x -1:47 core:backspace (input.hidden-input)
     -1:45 editor:consolidate-selections (input.hidden-input)
  2x -1:45 core:cancel (input.hidden-input)
  2x -1:39.3.0 core:backspace (input.hidden-input)
     -1:37.9.0 command-palette:toggle (input.hidden-input)
     -1:31.9.0 core:select-all (input.hidden-input)
     -1:26 core:confirm (input.hidden-input)
     -1:26 settings-view:install-packages-and-themes (input.hidden-input)
  2x -1:22.6.0 core:backspace (input.hidden-input)
     -1:13.1.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
script 3.29.3 
```

**Comment by aminya** [comment]
Please reinstall. This is a connection issue.
