### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by Utkarsh1504** [atom-community/atom-script#2378]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [script](https://github.com/atom-ide-community/atom-script) package 3.29.3

### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At C:\Users\HP\.atom\packages\script\lib\runner.js:136

TypeError: Cannot read property 'replace' of undefined
    at Runner.fillVarsInArg (/packages/script/lib/runner.js:136:17)
    at /packages/script/lib/runner.js:167:36
    at Array.map (<anonymous>)
    at Runner.args (/packages/script/lib/runner.js:167:18)
    at Runner.run (/packages/script/lib/runner.js:25:23)
    at Runtime.execute (/packages/script/lib/runtime.js:79:17)
    at HTMLElement.scriptRun (/packages/script/lib/script.js:98:40)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:350382)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:348857)
    at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:1:754178)
    at EventEmitter.t (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:1:762128)
    at EventEmitter.emit (events.js:200:13)
    at Object.onMessage (~/AppData/Local/atom/app-1.54.0/resources/electron.asar/renderer/init.js:42:16)
```

### Commands

```
     -8:23.6.0 autocomplete-plus:confirm (input.hidden-input)
     -8:16.8.0 editor:newline (input.hidden-input)
     -8:15.5.0 core:backspace (input.hidden-input)
  2x -8:13.7.0 core:move-right (input.hidden-input)
  2x -8:12.6.0 editor:newline (input.hidden-input)
     -8:09.9.0 autocomplete-plus:confirm (input.hidden-input)
  5x -8:04.1.0 core:backspace (input.hidden-input)
     -6:42.8.0 command-palette:toggle (input.hidden-input)
     -6:35.2.0 application:show-preferences (input.hidden-input)
  3x -4:35.3.0 script:run (input.hidden-input)
     -2:45.3.0 command-palette:toggle (div.am-panel.tool-panel.panel-bottom.native-key-bindings.script-view)
     -2:40.9.0 application:show-preferences (div.am-panel.tool-panel.panel-bottom.native-key-bindings.script-view)
     -1:12.7.0 script:run (div.tool-panel.tree-view)
  5x -0:59.7.0 core:backspace (input.hidden-input)
     -0:52.1.0 editor:newline (input.hidden-input)
     -0:47.6.0 script:run (input.hidden-input)
```

### Non-Core Packages

```
prettier-atom 0.60.1 
script 3.29.3 
```

**Comment by aminya** [comment]
Fixed in #2419
