### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by aarushsoni15** [atom-community/atom-script#2379]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [script](https://github.com/atom-ide-community/atom-script) package 3.29.3

### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At C:\Users\MyUsername\.atom\packages\script\lib\runner.js:136

TypeError: Cannot read property 'replace' of undefined
    at Runner.fillVarsInArg (/packages/script/lib/runner.js:136:17)
    at /packages/script/lib/runner.js:167:36
    at Array.map (<anonymous>)
    at Runner.args (/packages/script/lib/runner.js:167:18)
    at Runner.run (/packages/script/lib/runner.js:25:23)
    at Runtime.execute (/packages/script/lib/runtime.js:79:17)
    at HTMLElement.scriptRun (/packages/script/lib/script.js:98:40)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:350382)
    at KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:1230982)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:1227116)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:284879)
```

### Commands

```
     -1:07.2.0 script:close-view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-light-ui)
     -1:05.4.0 tree-view:add-file (div.header.list-item.project-root-header)
     -1:03.5.0 core:confirm (input.hidden-input)
  2x -0:59.1.0 core:backspace (input.hidden-input)
     -0:53.7.0 editor:newline (input.hidden-input)
     -0:52.1.0 autocomplete-plus:confirm (input.hidden-input)
     -0:52.1.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:49.7.0 autocomplete-plus:confirm (input.hidden-input)
     -0:49.7.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:48.7.0 core:backspace (input.hidden-input)
  3x -0:45.3.0 core:move-right (input.hidden-input)
  2x -0:44.4.0 core:delete (input.hidden-input)
     -0:40 script:run (input.hidden-input)
     -0:18.8.0 script:close-view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-light-ui)
     -0:16.8.0 core:save (input.hidden-input)
     -0:15.7.0 script:run (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-base 2.1.6 
atom-ide-datatip 0.22.0 
atom-ide-definitions 0.4.0 
atom-ide-hyperclick 1.0.9 
atom-ide-javascript 1.5.0 
atom-ide-markdown-service 1.6.0 
atom-ide-outline 1.16.0 
atom-ide-signature-help 0.13.2 
atom-live-server 2.3.0 
atom-python-run 0.9.7 
atom-typescript 14.1.2 
autocomplete-java 1.2.7 
autocomplete-paths 2.12.17 
busy-signal 2.0.1 
emmet 2.4.3 
gpp-compiler 3.0.7 
ide-clangd 0.4.0 
ide-java 0.9.1 
ide-python 1.7.2 
intentions 1.1.5 
javascript-drag-import 0.1.13 
linter 3.3.0 
linter-eslint 8.5.5 
linter-gcc 0.9.0 
linter-ui-default 2.4.1 
python-tools 0.6.9 
Quick-JavaScript 2.2.0 
script 3.29.3 
turbo-javascript 1.4.0 
x-terminal 12.1.2 
```

**Comment by aarushsoni15** [comment]
This happens to me when i try to run C programs using the Script package
