### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by Pra7ik** [atom-community/atom-script#2389]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home
**Thrown From**: [script](https://github.com/atom-ide-community/atom-script) package 3.29.3

### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At C:\Users\hp ryzen 5\.atom\packages\script\lib\runner.js:136

TypeError: Cannot read property 'replace' of undefined
    at Runner.fillVarsInArg (/packages/script/lib/runner.js:136:17)
    at /packages/script/lib/runner.js:167:36
    at Array.map (<anonymous>)
    at Runner.args (/packages/script/lib/runner.js:167:18)
    at Runner.run (/packages/script/lib/runner.js:25:23)
    at Runtime.execute (/packages/script/lib/runtime.js:79:17)
    at HTMLElement.scriptRun (/packages/script/lib/script.js:98:40)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:350382)
    at KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:1230982)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:1227116)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:284879)
```

### Commands

```
 22x -3:50.5.0 core:backspace (input.hidden-input)
     -3:17.6.0 tree-view:add-file (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:13.9.0 core:confirm (input.hidden-input)
  5x -3:08.6.0 core:backspace (input.hidden-input)
     -2:55.1.0 editor:newline (input.hidden-input)
  2x -2:48.8.0 core:move-right (input.hidden-input)
  2x -2:47.4.0 editor:newline (input.hidden-input)
  2x -2:28.1.0 core:move-right (input.hidden-input)
     -2:21.7.0 core:save (input.hidden-input)
     -2:15.3.0 fuzzy-finder:toggle-git-status-finder (input.hidden-input)
     -1:50.1.0 settings-view:open (div.tool-panel.tree-view)
     -0:14.9.0 script:run (input.hidden-input)
```

### Non-Core Packages

```
gpp-compiler 3.0.7 
script 3.29.3 
```

**Comment by Pra7ik** [comment]
can anyone help me i am just starting to code and i cannot run c programs
