### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by kidiksentrik** [atom-community/atom-script#2412]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Education
**Thrown From**: [script](https://github.com/atom-ide-community/atom-script) package 3.29.3

### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At C:\Users\Cooper\.atom\packages\script\lib\runner.js:136

TypeError: Cannot read property 'replace' of undefined
    at Runner.fillVarsInArg (/packages/script/lib/runner.js:136:17)
    at /packages/script/lib/runner.js:167:36
    at Array.map (<anonymous>)
    at Runner.args (/packages/script/lib/runner.js:167:18)
    at Runner.run (/packages/script/lib/runner.js:25:23)
    at Runtime.execute (/packages/script/lib/runtime.js:79:17)
    at HTMLElement.scriptRun (/packages/script/lib/script.js:98:40)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:350382)
    at KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:1230982)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:1227116)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:284879)
```

### Commands

```
     -1:14.5.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -1:06.5.0 core:confirm (input.hidden-input)
     -0:51.4.0 core:paste (input.hidden-input)
     -0:49.7.0 core:save (input.hidden-input)
  6x -0:39 core:backspace (input.hidden-input)
     -0:31.6.0 script:run (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
kite 0.204.0 
script 3.29.3 
```

**Comment by aminya** [comment]
Fixed in #2419
