### ISSUE TITLE
Failed to activate the script package

### ISSUE THREAD

**Issue by alifadityarahman** [atom-community/atom-script#2424]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [script](https://github.com/atom-ide-community/atom-script) package 3.29.6

### Stack Trace

Failed to activate the script package

```
At Cannot find module './code-context-builder'
Require stack:
- C:\Users\ASUS\.atom\packages\script\lib\script.js
- C:\Users\ASUS\AppData\Local\atom\app-1.55.0\resources\app.asar\static\index.html

Error: Cannot find module './code-context-builder'
Require stack:
- C:\Users\ASUS\.atom\packages\script\lib\script.js
- C:\Users\ASUS\AppData\Local\atom\app-1.55.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.55.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (<embedded>:11:155387)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (<embedded>:11:146720)
    at /packages/script/lib/script.js:15:27)
    at /packages/script/lib/script.js:283:3)
    at Module.get_Module._compile (<embedded>:11:147404)
    at Object.value [as .js] (<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (<embedded>:1:736637)
    at requireModule (<embedded>:14:1122229)
    at Package.requireMainModule (<embedded>:11:3509026)
    at Package.activateNow (<embedded>:11:3497010)
    at <embedded>:14:2607
    at Function.simpleDispatch (<embedded>:11:1190181)
    at Emitter.emit (<embedded>:11:1191622)
    at <embedded>:11:383936
    at Set.forEach (<anonymous>:null:null)
    at PackageManager.activatePackage (<embedded>:11:383898)
    at <embedded>:11:916751
    at r (<embedded>:11:911357)
    at n (<embedded>:14:1121552)
    at ChildProcess.<anonymous> (<embedded>:14:1121758)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)

```

### Commands

```
  2x -2:46.4.0 core:select-left (input.hidden-input)
     -2:45.8.0 core:paste (input.hidden-input)
     -2:44.9.0 core:undo (input.hidden-input)
  4x -2:41.4.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
busy-signal 2.0.1 
color-picker 2.3.0 
emmet 2.4.3 
file-icons 2.1.47 
ftp-remote-edit 0.18.1 
git-plus 8.7.1 
highlight-selected 0.17.0 
intentions 1.1.5 
javascript-snippets 1.2.1 
linter 3.3.0 
linter-ui-default 3.3.0 
minimap 4.39.10 
pigments 0.40.6 
script 3.29.6 
todo 0.6.0 
```

**Comment by aminya** [comment]
Please re-download. This is a connection/cache issue
