### ISSUE TITLE
Failed to activate the script package

### ISSUE THREAD

**Issue by Betty777JB** [atom-community/atom-script#2429]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home
**Thrown From**: [script](https://github.com/atom-ide-community/atom-script) package 3.31.1

### Stack Trace

Failed to activate the script package

```
At OperatingSystem.platform is not a function

TypeError: OperatingSystem.platform is not a function
    at /packages/script/lib/grammars/c.js:7:28)
    at /packages/script/lib/grammars/c.js:183:25)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:146720)
    at /packages/script/lib/grammars.js:5:18)
    at /packages/script/lib/grammars.js:46:24)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:146720)
    at /packages/script/lib/code-context-builder.js:5:41)
    at /packages/script/lib/code-context-builder.js:135:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:146720)
    at /packages/script/lib/script.js:3:43)
    at /packages/script/lib/script.js:239:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:1:723602)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:3670531)
    at Package.activateNow (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:3658515)
    at ~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:2607
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-live-server 2.3.0 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
busy-signal 2.0.1 
color-picker 2.3.0 
csslint 1.2.0 
emmet 2.4.3 
file-templates 0.2.0 
html-nested-comments 3.4.0 
hyperclick 0.1.5 
intentions 1.1.5 
language-ejs 0.4.0 
linter 3.3.0 
linter-eslint 8.6.2 
linter-ui-default 3.3.0 
pigments 0.40.6 
script 3.31.1 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by aminya** [comment]
Please re-download. That's an [apm issue](https://github.com/atom/apm/issues/919)

**Comment by aminya** [comment]
Please re-download. This is an apm issue

```
apm uninstall script
```
Clear your cache then

```
apm install script
```

https://github.com/atom/apm/issues/919
