### ISSUE TITLE
Failed to activate the script package

### ISSUE THREAD

**Issue by ismail188** [atom-community/atom-script#2432]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home
**Thrown From**: [script](https://github.com/atom-ide-community/atom-script) package 3.31.1

### Stack Trace

Failed to activate the script package

```
At Cannot find module 'C:\Users\Ismail\.atom\packages\script\node_modules\uuid\dist\index.js'. Please verify that the package.json has a valid "main" entry

Error: Cannot find module 'C:\Users\Ismail\.atom\packages\script\node_modules\uuid\dist\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:232:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:369:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:614:27)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.55.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:155387)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:146720)
    at /packages/script/lib/grammar-utils/matlab.js:6:24)
    at /packages/script/lib/grammar-utils/matlab.js:36:34)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:146720)
    at /packages/script/lib/grammar-utils.js:96:11)
    at /packages/script/lib/grammar-utils.js:128:28)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:146720)
    at /packages/script/lib/grammars/index.js:12:24)
    at /packages/script/lib/grammars/index.js:614:29)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
```

### Commands

```
```

### Non-Core Packages

```
kite 0.204.0 
run 0.0.1 
run-python-simply 0.6.0 
script 3.31.1 
vk-terminal 3.0.1 
```

**Comment by aminya** [comment]
Please re-download. This is an apm issue

```
apm uninstall script
```
Clear your cache then

```
apm install script
```

https://github.com/atom/apm/issues/919
