### ISSUE TITLE
Failed to activate the script package

### ISSUE THREAD

**Issue by Horlaitan15** [atom-community/atom-script#2448]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [script](https://github.com/atom-ide-community/atom-script) package 3.31.1

### Stack Trace

Failed to activate the script package

```
At Cannot find module 'temp'
Require stack:
- C:\Users\HP\.atom\packages\script\lib\grammar-utils.js
- C:\Users\HP\.atom\packages\script\lib\grammars\index.js
- C:\Users\HP\.atom\packages\script\lib\grammars.js
- C:\Users\HP\.atom\packages\script\lib\code-context-builder.js
- C:\Users\HP\.atom\packages\script\lib\script.js
- C:\Users\HP\AppData\Local\atom\app-1.55.0\resources\app.asar\static\index.html

Error: Cannot find module 'temp'
Require stack:
- C:\Users\HP\.atom\packages\script\lib\grammar-utils.js
- C:\Users\HP\.atom\packages\script\lib\grammars\index.js
- C:\Users\HP\.atom\packages\script\lib\grammars.js
- C:\Users\HP\.atom\packages\script\lib\code-context-builder.js
- C:\Users\HP\.atom\packages\script\lib\script.js
- C:\Users\HP\AppData\Local\atom\app-1.55.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.55.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:155387)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:146720)
    at /packages/script/lib/grammar-utils.js:6:24)
    at /packages/script/lib/grammar-utils.js:128:28)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:146720)
    at /packages/script/lib/grammars/index.js:12:24)
    at /packages/script/lib/grammars/index.js:614:29)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:146720)
    at /packages/script/lib/grammars.js:11:22)
    at /packages/script/lib/grammars.js:46:24)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:146720)
    at /packages/script/lib/code-context-builder.js:5:41)
```

### Commands

```
```

### Non-Core Packages

```
script 3.31.1 
server-script 0.1.3 
```

**Comment by aminya** [comment]
Please re-download. This is an apm issue

```
apm uninstall script
```
Clear your cache then

```
apm install script
```

https://github.com/atom/apm/issues/919
