### ISSUE TITLE
Failed to activate the script package

### ISSUE THREAD

**Issue by AshutoshJha786** [atom-community/atom-script#2472]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [script](https://github.com/atom-ide-community/atom-script) package 3.32.1

### Stack Trace

Failed to activate the script package

```
At Cannot find module '../grammar-utils'
Require stack:
- C:\Users\DELL\.atom\packages\script\lib\grammars\index.js
- C:\Users\DELL\.atom\packages\script\lib\grammars.js
- C:\Users\DELL\.atom\packages\script\lib\code-context-builder.js
- C:\Users\DELL\.atom\packages\script\lib\script.js
- C:\Users\DELL\AppData\Local\atom\app-1.57.0\resources\app.asar\static\index.html

Error: Cannot find module '../grammar-utils'
Require stack:
- C:\Users\DELL\.atom\packages\script\lib\grammars\index.js
- C:\Users\DELL\.atom\packages\script\lib\grammars.js
- C:\Users\DELL\.atom\packages\script\lib\code-context-builder.js
- C:\Users\DELL\.atom\packages\script\lib\script.js
- C:\Users\DELL\AppData\Local\atom\app-1.57.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (<embedded>:11:157820)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (<embedded>:11:149153)
    at /packages/script/lib/grammars/index.js:20:21)
    at /packages/script/lib/grammars/index.js:703:3)
    at Module.get_Module._compile (<embedded>:11:149837)
    at Object.value [as .js] (<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (<embedded>:11:149153)
    at /packages/script/lib/grammars.js:11:22)
    at /packages/script/lib/grammars.js:93:3)
    at Module.get_Module._compile (<embedded>:11:149837)
    at Object.value [as .js] (<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (<embedded>:11:149153)
    at /packages/script/lib/code-context-builder.js:20:17)
    at /packages/script/lib/code-context-builder.js:180:3)
    at Module.get_Module._compile (<embedded>:11:149837)
    at Object.value [as .js] (<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (<embedded>:11:149153)
    at /packages/script/lib/script.js:15:27)
    at /packages/script/lib/script.js:290:3)
    at Module.get_Module._compile (<embedded>:11:149837)
    at Object.value [as .js] (<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (<embedded>:1:802772)
    at requireModule (<embedded>:14:1191588)
    at Package.requireMainModule (<embedded>:11:3520819)
    at Package.activateNow (<embedded>:11:3508803)
    at <embedded>:14:2607
    at Function.simpleDispatch (<embedded>:11:1186190)
    at Emitter.emit (<embedded>:11:1187631)
    at <embedded>:11:385787
    at Set.forEach (<anonymous>:null:null)
    at PackageManager.activatePackage (<embedded>:11:385749)
    at <embedded>:11:914488
    at r (<embedded>:11:909094)
    at n (<embedded>:14:1190911)
    at ChildProcess.<anonymous> (<embedded>:14:1191117)
    at ChildProcess.emit (events.js:223:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)

```

### Commands

```
     -2:33.3.0 settings-view:open (div.tool-panel.tree-view)
     -1:09.8.0 fuzzy-finder:toggle-git-status-finder (input.hidden-input)
     -0:58.9.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
language-terraform 0.9.6 
script 3.32.1 
```

**Comment by aminya** [comment]
Please re-download. This is an apm issue

```
apm uninstall script
```
Clear your cache then

```
apm install script
```

https://github.com/atom/apm/issues/919
