### ISSUE TITLE
Failed to activate the script package

### ISSUE THREAD

**Issue by trripy** [atom-community/atom-script#2484]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [script](https://github.com/atom-ide-community/atom-script) package 3.32.2

### Stack Trace

Failed to activate the script package

```
At Cannot find module 'ansi-to-html'
Require stack:
- C:\Users\kanka\.atom\packages\script\lib\script-view.js
- C:\Users\kanka\.atom\packages\script\lib\script.js
- C:\Users\kanka\AppData\Local\atom\app-1.57.0\resources\app.asar\static\index.html

Error: Cannot find module 'ansi-to-html'
Require stack:
- C:\Users\kanka\.atom\packages\script\lib\script-view.js
- C:\Users\kanka\.atom\packages\script\lib\script.js
- C:\Users\kanka\AppData\Local\atom\app-1.57.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:157820)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149153)
    at /packages/script/lib/script-view.js:23:19)
    at /packages/script/lib/script-view.js:303:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149153)
    at /packages/script/lib/script.js:43:19)
    at /packages/script/lib/script.js:290:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:1:802772)
    at requireModule (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:1191588)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:3520819)
    at Package.activateNow (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:3508803)
    at ~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1186190)
    at Emitter.emit (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1187631)
```

### Commands

```
 13x -4:14.9.0 core:backspace (input.hidden-input)
     -4:10.6.0 core:confirm (input.hidden-input)
     -4:02.4.0 core:backspace (input.hidden-input)
     -3:10.7.0 core:move-right (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
script 3.32.2 
```

**Comment by aminya** [comment]
Please re-download. This is an apm issue

```
apm uninstall script
```
Clear your cache then

```
apm install script
```

https://github.com/atom/apm/issues/919

**Comment by Ninjagor** [comment]
I got "Script failed to activate" I tried redowloading, still didnt work. Help?
