### ISSUE TITLE
Failed to activate the script package

### ISSUE THREAD

**Issue by rohit123dey** [atom-community/atom-script#2495]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [script](https://github.com/atom-ide-community/atom-script) package 3.32.2

### Stack Trace

Failed to activate the script package

```
At Cannot find module 'atom-space-pen-views-plus'
Require stack:
- C:\Users\Rohit\.atom\packages\script\lib\script-options-view.js
- C:\Users\Rohit\.atom\packages\script\lib\script.js
- C:\Users\Rohit\AppData\Local\atom\app-1.57.0\resources\app.asar\static\index.html

Error: Cannot find module 'atom-space-pen-views-plus'
Require stack:
- C:\Users\Rohit\.atom\packages\script\lib\script-options-view.js
- C:\Users\Rohit\.atom\packages\script\lib\script.js
- C:\Users\Rohit\AppData\Local\atom\app-1.57.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:157820)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149153)
    at /packages/script/lib/script-options-view.js:3:52)
    at /packages/script/lib/script-options-view.js:8:39)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149153)
    at /packages/script/lib/script.js:9:45)
    at /packages/script/lib/script.js:239:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:1:802772)
    at requireModule (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:1191588)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:3520819)
    at Package.activateNow (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:3508803)
    at ~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1186190)
    at Emitter.emit (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1187631)
    at PackageManager.triggerDeferredActivationHooks (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:385941)
    at ~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:384692
```

### Commands

```
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
csslint 1.2.0 
emmet 2.4.3 
hyperclick 0.1.5 
language-ejs 0.4.0 
linter-eslint 8.6.6 
package-script-runner 1.0.0 
pigments 0.40.6 
script 3.32.2 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by AtomStriker** [comment]
I've got the same problem
![image](https://user-images.githubusercontent.com/82794559/120930972-a2c9e580-c700-11eb-8c9b-4ca8e719fdb8.png)
