### ISSUE TITLE
Uncaught Error: Cannot find module '$ATOM_HOME/packages\script\node_modules\temp\lib\temp'. Pleas...

### ISSUE THREAD

**Issue by Stormbender0025** [atom-community/atom-script#2537]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [script](https://github.com/atom-ide-community/atom-script) package 3.32.2

### Stack Trace

Uncaught Error: Cannot find module 'C:\Users\Dell\.atom\packages\script\node_modules\temp\lib\temp'. Please verify that the package.json has a valid "main" entry

```
At internal/modules/cjs/loader.js:240

Error: Cannot find module 'C:\Users\Dell\.atom\packages\script\node_modules\temp\lib\temp'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:232:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:369:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:614:27)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.52.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:155481)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:146814)
    at /packages/script/lib/grammar-utils.js:6:24)
    at /packages/script/lib/grammar-utils.js:128:28)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:146814)
    at /packages/script/lib/grammars/index.js:12:24)
    at /packages/script/lib/grammars/index.js:614:29)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:146814)
    at /packages/script/lib/grammars.js:11:22)
    at /packages/script/lib/grammars.js:46:24)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-java-snippets 0.5.1 
autocomplete-java 1.2.7 
language-arm 2.1.1 
language-rainmeter 1.7.5 
language-x86asm 0.9.0 
script 3.32.2 
serenade 1.4.5 
TabNine undefined 
tree-view-sort 0.12.1 
```

**Comment by Stormbender0025** [comment]
I reinstalled Script and its working again!
