### ISSUE TITLE
Failed to activate the script package

### ISSUE THREAD

**Issue by shehav9999** [atom-community/atom-script#2549]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [script](https://github.com/atom-ide-community/atom-script) package 3.32.2

### Stack Trace

Failed to activate the script package

```
At Cannot find module './code-context-builder'
Require stack:
- C:\Users\SHEHAB\.atom\packages\script\lib\script.js
- C:\Users\SHEHAB\AppData\Local\atom\app-1.58.0\resources\app.asar\static\index.html

Error: Cannot find module './code-context-builder'
Require stack:
- C:\Users\SHEHAB\.atom\packages\script\lib\script.js
- C:\Users\SHEHAB\AppData\Local\atom\app-1.58.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:157920)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149207)
    at /packages/script/lib/script.js:15:27)
    at /packages/script/lib/script.js:290:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:1:802772)
    at requireModule (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:1195622)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3520513)
    at Package.activateNow (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3508497)
    at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:1186925)
    at Emitter.emit (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:1188366)
    at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:385902
    at Set.forEach (<anonymous>)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:385864)
    at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:915033
    at r (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:909639)
    at n (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:1194945)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:1195151)
    at ChildProcess.emit (events.js:223:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

### Commands

```
     -1:12.5.0 application:open-folder (input.hidden-input)
```

### Non-Core Packages

```
script 3.32.2 
```

**Comment by shehav9999** [comment]
;km
